package edu.harvard.countway.mhl.archivespark.search

object MhlCollections {
  case class MhlCollection(id: String)
  private def set(ids: String*) = ids.toSet.map(MhlCollection)
  
  val Additional_Collections = set("additional_collections")
  val Americana = set("americana")
  val Aphmigel = set("aphmigel")
  val Chemistanddruggist = set("chemistanddruggist")
  val Cms = set("cms")
  val Cmslibrary = set("cmslibrary")
  val Collegeofphysiciansofphiladelphia = set("collegeofphysiciansofphiladelphia")
  val Columbiauniversitylibraries = set("columbiauniversitylibraries")
  val Congress = set("congress")
  val Culturalandacademicfilms = set("culturalandacademicfilms")
  val Cushingwhitneymedicallibrary = set("cushingwhitneymedicallibrary")
  val Europeanlibraries = set("europeanlibraries")
  val Fedlink = set("fedlink")
  val Francisacountwaylibrary = set("francisacountwaylibrary")
  val Gerstein = set("gerstein")
  val Globallibraries = set("globallibraries")
  val Kingscollegelondon = set("kingscollegelondon")
  val Leedsuniversitylibrary = set("leedsuniversitylibrary")
  val Lshtmlibrary = set("lshtmlibrary")
  val Medicalheritagelibrary = set("medicalheritagelibrary")
  val Medicalofficerofhealthreports = set("medicalofficerofhealthreports")
  val Medicineintheamericas = set("medicineintheamericas")
  val Newsandpublicaffairs = set("newsandpublicaffairs")
  val Nihlibrary = set("nihlibrary")
  val Nlmpublications = set("nlmpublications")
  val Nyamlibrary = set("nyamlibrary")
  val Pubs = set("pubs")
  val Rcpedinburgh = set("rcpedinburgh")
  val Rcplondon = set("rcplondon")
  val Rcseng = set("rcseng")
  val Related = set("related")
  val Reports = set("reports")
  val Ssa = set("ssa")
  val Statemedicalsocietyjournals = set("statemedicalsocietyjournals")
  val Tobaccoarchives = set("tobaccoarchives")
  val Toronto = set("toronto")
  val Ucllibrary = set("ucllibrary")
  val Ucsanfranciscolibrary = set("ucsanfranciscolibrary")
  val Ukmhl = set("ukmhl")
  val Umarylandbaltimoredigitalarchive = set("umarylandbaltimoredigitalarchive")
  val Unchs = set("unchs")
  val Unclibraries = set("unclibraries")
  val University_of_toronto = set("university_of_toronto")
  val Universityofbristol = set("universityofbristol")
  val Universityofglasgow = set("universityofglasgow")
  val Us = set("us")
  val Usnationallibraryofmedicine = set("usnationallibraryofmedicine")
  val Usnavybumedhistoryoffice = set("usnavybumedhistoryoffice")
  val Wellcomefilm = set("wellcomefilm")
  val Wellcomelibrary = set("wellcomelibrary")

  def All = Additional_Collections ++ Americana ++ Aphmigel ++ Chemistanddruggist ++ Cms ++ Cmslibrary ++ Collegeofphysiciansofphiladelphia ++ Columbiauniversitylibraries ++ Congress ++ Culturalandacademicfilms ++ Cushingwhitneymedicallibrary ++ Europeanlibraries ++ Fedlink ++ Francisacountwaylibrary ++ Gerstein ++ Globallibraries ++ Kingscollegelondon ++ Leedsuniversitylibrary ++ Lshtmlibrary ++ Medicalheritagelibrary ++ Medicalofficerofhealthreports ++ Medicineintheamericas ++ Newsandpublicaffairs ++ Nihlibrary ++ Nlmpublications ++ Nyamlibrary ++ Pubs ++ Rcpedinburgh ++ Rcplondon ++ Rcseng ++ Related ++ Reports ++ Ssa ++ Statemedicalsocietyjournals ++ Tobaccoarchives ++ Toronto ++ Ucllibrary ++ Ucsanfranciscolibrary ++ Ukmhl ++ Umarylandbaltimoredigitalarchive ++ Unchs ++ Unclibraries ++ University_of_toronto ++ Universityofbristol ++ Universityofglasgow ++ Us ++ Usnationallibraryofmedicine ++ Usnavybumedhistoryoffice ++ Wellcomefilm ++ Wellcomelibrary
}